### ISSUE TITLE
【翻译】DOC-03-6 Globalization and localization

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#100]
Document Urls：https://docs.asp.net/en/latest/fundamentals/localization.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/localization.rst

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
36 | 我将展示 IStringLocalizer 服务如何被添加 Configuring localization 章节 | 在Configuring localization 章节，我将展示如何添加 IStringLocalizer 服务 | 
37 | 并在使用 localizer 包装他们，这样你可以专注于开发应用程序 | 然后再使用 localizer 包装他们，这样你就可以专注于开发应用程序 | 
39 | IHtmlLocalizer HTML encodes 参数是格式化过的资源字符串，而不是原始字符串 | IHtmlLocalizer 对格式化过的资源字符串参数进行编码，而不是对原始资源字符串 | 
48 | 在最低级别, 你可以在 Dependency Injection 之外获取 IStringLocalizerFactory | 在最低层次, 你可以通过 Dependency Injection 获取 IStringLocalizerFactory |
96 |  |  |  忘记翻译了
98 | 在视图中试用共享资源文件，注入 IHtmlLocalizer<T>: |  为了在视图中试用共享资源文件，需要注入 IHtmlLocalizer<T>: |  
134 | 对于非默认语言翻译字符串 | 非默认语言翻译字符串 | 
140 | 您可能希望创建一个名为 Welcome.es.resx 的资源文件西班牙语翻译字符串 | 您可能希望创建一个名为 Welcome.es.resx 的西班牙语资源文件来包含翻译字符串 |
140 | 要创建在Visual Studio这样的资源文件 | 在Visual Studio中，这样创建资源文件 | 
142 |  |  | 翻译不完整
154 | Visual Studio 展示 Welcome.es.resx 文件  |  Visual Studio 展示出 Welcome.es.resx 文件 |  
215 | 例如，同样的区域性信息都惠子设置在 Culture and the UICulture 之上 | 例如，仅设置culture，将会同样设置 Culture 和 UICulture | 
222，224 | ~Microsoft.AspNetCore.Localization.CookieRequestCultureProvider.MakeCookieValue |   | 和原文不一致
334 |  RFC 4646 是用语言和一个国家或地区相关的ISO3166双字母大写子代码关联的ISO 639双字母小写区域性代码的组合 |  RFC 4646 是用与语言相关的ISO 639双字母小写区域性代码和一个与国家或地区相关的ISO3166双字母大写子代码组合 |

**Comment by kiler398** [comment]
剩下这2个问题没有修正
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
142 |  |  | 翻译不完整
222，224 | ~Microsoft.AspNetCore.Localization.CookieRequestCultureProvider.MakeCookieValue |   | 和原文不一致
