### ISSUE TITLE
【翻译】DOC-03-7 Configuration

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#101]
Document Urls：https://docs.asp.net/en/latest/fundamentals/configuration.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/configuration.rst

**Comment by mengshuaiyang** [comment]
1.第18行 [你也编写自己的自定义配置提供程序。] 修改为 [你也可以编写自己的自定义配置提供程序。]
 2.第69行 [在此情况下，可以使用以“:”符号分隔] 修改为 [在此情况下，可以使用以 ``:`` 符号分隔]
 3.第223行 [通过调用 ``Configure<TOption>`` 将一个个 ``IConfigureOptions<TOption>`` 服务加入服务容器] 修改为 [通过调用 ``Configure<TOption>`` 将一个 ``IConfigureOptions<TOption>`` 服务加入服务容器]

@alexinea
