### ISSUE TITLE
【翻译】DOC-03-10 Dependency Injection

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#103]
Document Urls：https://docs.asp.net/en/latest/fundamentals/dependency-injection.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/dependency-injection.rst

**Comment by jack2gs** [comment]
行号 | 原文 | 修改建议 | 备注
---- | ---- | ---- | ----
16 | ASP.NET Core 被设计为从底层支持和利用依赖注入 | ASP.NET Core 的底层设计支持和使用依赖注入。 | 
269 | 设计你的服务支持依赖注入 | 设计你的依赖注入服务 | 
288 | 更换默认的服务容器 | 替换默认的服务容器 |
37 | 因为它们没有直接硬编码的依赖于它们的合作者 | 因为它们没有对它们的合作者直接硬编码的依赖 |
102 | AddTransient 方法用于抽象类型映射到分别为每一个需要它的对象实例化的具体服务 | AddTransient 方法用于将抽象类型映射到为每一个需要它的对象分别实例化的具体服务 |
102 | 另外的生命周期选项在下面描述 | 其他的生命周期选项在下面描述 | 
106 | 并且初始化具有少量字符的集合如果它不存在的话 | 并且如果它不存在的话则初始化具有少量字符的集合 | 
155 | 仓储将引用 Entity Framework 应该使用相同的生命周期 | 仓储将使 Entity Framework 使用相同的生命周期 | 
212 | 因此在一个请求中对于每个操作类型，该服务获取相同的实例或一个新的实例作为控制器将是明确的 | 因此在一个请求中对于每个操作类型，该服务获取相同的实例或创建一个新的实例作为控制器将是明确的 |
251 | 在一次 ASP.NET 请求内从 HttpContext 所提供的服务是通过 RequestServices 集合公开的。 | 来自HttpContext的一次ASP.NET请求中可用的服务通过 RequestServices 集合公开的。 |
257 | 请求服务代理你配置和请求的服务作为你的应用程序的一部分 | 请求服务将你配置的服务和请求描述为应用程序的一部分。
257 | 当你的对象指定依赖关系，这些满足的类型被发现在 RequestServices，而不是 ApplicationServices | 当你的对象指定依赖关系，这些满足要求的对象通过查找RequestServices中对应的类型得到，而不是 ApplicationServices |
261 | 这将会生成更方便测试 | 这将会生成更易于测试的 |
274 | 你应该设计你的服务使用依赖注入来获取它们的合作者 | 你应该设计你的依赖注入服务来获取它们的合作者 |
274 | 你的类通常会更小，结构合理和易于测试 | 你的类将倾向于比较小，已分解的及易于测试的。 |
278 | 因此业务规则和数据访问实现细节应该适当的保存在这些单独关注的类中 | 因此业务规则和数据访问实现细节应该保存在这些适合单独关注的类中 |
293 | 内置的服务容器的意义在于提供框架的基本需求并且大多数消费者的应用程序建立在它之上 | 内置的服务容器的意图在于提供框架的基本需求并且大多数客户应用程序建立在它之上 |
293 | 希望使用他们的首选容器替换默认容器的开发人员可以很容易的这样做 | 开发人员可以很容易地使用他们的首选容器替换默认容器 |
