### ISSUE TITLE
【翻译】DOC-03-11 Working with Multiple Environments

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#104]
Document Urls：https://docs.asp.net/en/latest/fundamentals/environments.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/environments.rst

**Comment by mengshuaiyang** [comment]
1.第6行 [By `Steve Smith`] 修改为 [作者： `Steve Smith`]
 2.第73行 [在这里它们可以解决而不影响到用户。] 修改为 [在这里可以解决它们而不影响到用户。]
 3.第82行 [``Production``] 移除前面的空格
 4.第94行 [for example, Application Insights] 修改为 [例如 Application Insights]
 5.第107行 [``IHostingEnvironment``] 移除前面的空格
 6.第175行 [设置为 ``Staging``时， ``StartupStaging`` 类被使用]  Staging及StartupStaging``后缺少空格

需修改上述问题，同时需对比[原文](https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/environments.rst) 把内容修改至1.0.0 版本

@liuhaoyang
