### ISSUE TITLE
【翻译】DOC-03-13 Managing Application State

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#105]
Document Urls：https://docs.asp.net/en/latest/fundamentals/app-state.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/app-state.rst

**Comment by YaoaY** [comment]
已更新到最新版本， @kiler398

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
33 | 以及其他很多种状态储存的支持 | 以及其他很多种状态 **存储** 的支持 | 
37 |  | 去掉“注意：”  | 原文中没有
59 | 应用程序状态 | 应用程序**的**状态 | 
69 | 可以作为组件和中 | **它**可以作为组件和中 | 
71、76 |  |   | 这两行反了
100 | 安装和配置 Session |  | 链接缺失
171 |  如：采用”MyComponent.isVerified”，而非简单的”isVerified” |  |  引号标点符号错了
195 |  ”.AspNet.Session”  |  | 标点符号错了
241 |  |  | 这行之前应该加个空行吧
253 | 任何来到网站的请求穿过 | 任何来到网站的请求**通过** | 
257 | 被实现为一个 |  | 格式错误，应该加粗
366 | 如果``Session``中没有这个对象 | | 格式错误
370 | 点击”建立会话”链接发起一个对路径”/session”的访问请求 |  | 引号格式错了
419 | 注意这个中间件是在 app.UseSession 被调用（第13行）**之前** 就配置好的 |  | 格式错误

**Comment by jack2gs** [comment]
71、76行，Querystring应该是QueryString

**Comment by YaoaY** [comment]
已经修改。 @jack2gs 

[8d43fef](https://github.com/dotnetcore/aspnetcore-doc-cn/commit/8d43fefa1b230476857757b8db42ee17003a6ea1)
