### ISSUE TITLE
【翻译】DOC-03-16 Open Web Interface for .NET (OWIN)

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#107]
Document Urls：https://docs.asp.net/en/latest/fundamentals/owin.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/owin.rst

**Comment by mengshuaiyang** [comment]
1.第16行 [基于 OWIN 应用程序] 修改为 [OWIN-based 应用程序]
 2.第131行 [在基于OWIN服务器上运行 ASP.NET Core ，并且使用 WebSockets 支持] 修改为[在 OWIN-based 服务器上运行 ASP.NET Core 并使用 WebSockets 支持]

基本的语法错误和标点符号错误已经修改过了，上面的两个需要你再确认一下，因为读起来不顺。可以使用：OWIN-based（基于 OWIN ），这种写法。另外需要你与最新版的内容（[原文](https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/owin.rst)）对比一下,有稍微的修改。

@kiler398

**Comment by kiler398** [comment]
改了 @mengshuaiyang
