### ISSUE TITLE
【翻译】DOC-0 Introduction to ASP.NET Core

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#171]
Document Urls：https://docs.asp.net/en/latest/intro.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/intro.rst

**Comment by ChujianA** [comment]
1、It was architected to provide an optimized development framework for apps that are deployed to the cloud or run on-premises.
它是为那些部署在云端或者预制运行（on-premises）的应用提供一个优化的开发框架的架构。
2、它是由具有最小化开销的多个模块组建组成的。
3、This allows you to optimize your app to include just the NuGet packages you need.
   这点允许你仅仅包含需要的NuGet包来优化你的应用程序。
4.WebHostBuilder  provides many optional methods including  UseIISIntegration  for hosting in IIS and IIS Express
  WebHostBuilder提供了一些可选方法，包括寄宿在IIS和IIS Express的UseIISIntegration方法
5.The  UseStartup  method on  WebHostBuilder  specifies the  Startup  class for your app。
WebHostBuilder  的  UseStartup  方法为你的应用指定了  Startup  类。
6、The web root of your app is the directory in your project for public, static resources like css, js, and image files
  你应用程序的web根是你项目中公共的目录，静态资源，像css,js和图片文件            （不确定对不对）
7、 You can also write your own custom configuration providers.
     你也可以写你自己定义的配置提供者
8、:doc:`Tag Helpers </mvc/views/tag-helpers/intro>` enable server-side code to participate in creating and rendering HTML elements in Razor files
   :doc:`Tag Helpers </mvc/views/tag-helpers/intro>` 让你的服务器端的代码参与到在Razor 文件中创建和展现HTML 元素中。

**Comment by YaoaY** [comment]
ASP.NET Core is a new open-source and cross-platform framework for building modern cloud based internet connected applications, such as web apps, IoT apps and mobile backends.

ASP.NET Core 是一个可用来构建如Web应用程序、IoT应用和移动应用后端等等现代的、基于云的互联网的可连接程序的全新开源跨平台的框架。

建议：
ASP.NET Core 是一个全新的开源跨平台框架，可用来构建诸如 Web 应用程序、IoT 应用和移动后端等连接到互联网的基于云的现代应用程序。

===================
It was architected to provide an optimized development framework for apps that are deployed to the cloud or run on-premises.

构建它的目的是为那些部署在云端或者预制运行（on-premises）的应用提供一个优化的开发框架。

建议：

它旨在为部署到云端或运行在本地的应用提供一个优化的开发框架。

微软官方通常将 on-premises 翻译为“本地”或“内部部署”

====================
It consists of modular components with minimal overhead, so you retain flexibility while constructing your solutions.

它由多个模块化最小化开销的组件构成，因此在构建你的解决方案的同时可以获得更多的灵活性。

建议：
它由最小化开销的模块组件组成，因此在构造你的解决方案时能够保持灵活性。
