### ISSUE TITLE
【翻译】DOC-3-2 choosing-the-right-dotnet.rst

### ISSUE THREAD

**Issue by wjhgzx** [dotnetcore/aspnetcore-doc-cn#174]
原文：https://docs.asp.net/en/latest/conceptual-overview/choosing-the-right-dotnet.html
翻译稿：https://github.com/wjhgzx/aspnetcore-doc-cn/blob/master/aspnet/conceptual-overview/choosing-the-right-dotnet.rst

**Comment by kiler398** [comment]
#202 我的修订意见，你看下，如果觉得调整不多就我来调整我的pr你那里接收，或者你这边自己修改一下。

**Comment by wjhgzx** [comment]
已经更新了，提交到我的fork项目中了。https://github.com/wjhgzx/aspnetcore-doc-cn/blob/master/aspnet/conceptual-overview/choosing-the-right-dotnet.rst
