### ISSUE TITLE
DOC-04-4-4 issue 重新关联

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/aspnetcore-doc-cn#184]
URL：https://docs.asp.net/en/latest/mvc/controllers/filters.html

翻译地址：https://github.com/alexinea/aspnetcore-doc-cn/blob/branch-mvc-controller-filter/aspnet/mvc/controllers/filters.rst

（基于20160523）

**Comment by kiler398** [comment]
#272 重新关联新的issue，本issue作废
