### ISSUE TITLE
【翻译】DOC-02-8 Developing ASP.NET Core applications using dotnet watch

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#191]
原文：https://docs.asp.net/en/latest/tutorials/dotnet-watch.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/dotnet-watch.rst

**Comment by alexinea** [comment]
第27行：
> 在本教程中，我们将使用一个现有的计算两个数字之和以及乘积的  WebAPI 应用程序来展示 ``dotnet watch`` 使用案例。示例应用程序故意包含一个错误，作为本教程的一部分我们会修复它。

建议改为：

> 在本教程中，我们将使用一个现有的计算两个数字之和以及乘积的  WebAPI 应用程序来演示如何使用 ``dotnet watch``。示例应用程序故意包含一个错误，作为本教程的一部分我们会修复它。

***

另外第 37、70 行中存在以下格式错误：
+ 英文和中文之间缺少一个半角空格。

**Comment by SeayXu** [comment]
第75行：
原文：打开一个**提升过权限**的 PowerShell 窗口
建议：打开一个**授权**的 PowerShell 窗口

第105行：
原文：在 Nano server 上创建文件共享这样可以直接拷贝发布的程序，在远程服务器上运行**下述**命令
建议：在 Nano server 上创建文件共享**，**这样可以直接拷贝发布的程序，在远程服务器上运行**下面的**命令

第115行：Windows Explorer 在计算机中是 Windows 资源管理器
原文：**上述**命令运行完以后，你就可以在你本机使用 **Windows 文件浏览器**通过
建议：**上面**命令运行完以后，你就可以在你本机使用 **Windows 资源管理器**通过

第123行：
原文：在远程会话中运行下面的命令在防火墙中打开一个端口来监听TCP流量。
建议：在远程会话中运行下面的命令**，**在防火墙中打开一个端口来监听 TCP 流量。

第152行：
原文：为了快速验证**ISS**是否正确安装
建议：为了快速验证 **IIS** 是否正确安装

第159行：
原文：ASP.NET Core Module 是一个适用于 IIS 7.5 及**以上**版本的组件...安装之后**您**需要将以下文件复制到我们前面创建的共享文件
建议：ASP.NET Core Module 是一个适用于 IIS 7.5 及**更高**版本的组件...安装之后**你**需要将以下文件复制到我们前面创建的共享文件

第163行：
原文：在常规机（不是 Nano Server）上运行**下述**拷贝命令
建议：在常规机（不是 Nano Server）上运行**下面**拷贝命令

第214行：
原文：**您**可能需要修改你的
建议：**你**可能需要修改你的

第235行：
原文：在远程会话中运行以下命令在**IIS**中为已发布的应用创建一个新的站点。
建议：在远程会话中运行以下命令**，**在 **IIS** 中为已发布的应用创建一个新的站点。

@kiler398 #190

**Comment by SeayXu** [comment]
第27行：
原文：WebAPI
建议：WebApi

第49行：
原文：控制台输出将显示如下信息，**指示**该应用程序正在运行并等待请求：
建议：控制台输出将显示如下信息，**表明**该应用程序正在运行并等待请求：

第132行：
原文：**限制** `dotnet watch` 现在正在监控代码文件
建议：**表明** `dotnet watch` 现在正在监控代码文件

第179行：
原文：**指示** `dotnet watch` 检测到文件的改变并重启了应用程序
建议：**表明** `dotnet watch` 检测到文件的改变并重启了应用程序
#198 @kiler398
