### ISSUE TITLE
【修订】DOC-03-3 Working with Static Files

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/aspnetcore-doc-cn#213]
Document Urls：https://docs.asp.net/en/latest/fundamentals/static-files.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/static-files.rst

1.0.0 版本已发送 PR （ #212 ）

ms1 位于 #96

**Comment by mengshuaiyang** [comment]
1. 第35行 [静态文件通常位于 web root` (<content-root>/wwwroot)文件夹下。] 修改为 [静态文件通常位于 ``web root`` (*< content-root>/wwwroot*)文件夹下。]
 2. 第37行 [你通常会把项目对当前目录设置为 Content root] 修改为 [你通常会把项目的当前目录设置为 Content root]
 3. 第47行 [当你通过 Visual Studio 创建了个默认的 Web 应用程序项目] 修改为 [当你通过 Visual Studio 创建了一个默认的 Web 应用程序项目]
 4. 第65行 [使得 web root （wwwroot by default） 下的文件可以被访问] 修改为 [使得 web root （默认情况下为wwwroot） 下的文件可以被访问]
 5. 第115行 [将文件保存在 wwwroot 之外并将目录设置为可悲静态文件中间件访问到，同时] 修改为 [将文件保存在 wwwroot 之外并将目录设置为可被静态文件中间件访问到]
 6. 第122行 [Directory browsing is disabled by default for security reasons (see Considerations_).] 翻译遗漏
 7. 第154行 [第一个调用请求 wwwroot 文件夹下的 CSS、图片和 JavaScript] 修改为 [第一个调用请求 wwwroot 文件夹下的 CSS、images 和 JavaScript]
 8. 第289行和第333行 【和、UseDirectoryBrowser】 前``缺少空格
 9. 第298 [See MIME 内容类型 。] 修改为 [查看 MIME 内容类型。]
 10. 第333行 [我们推荐你**不要**在生产环境开启目录浏览] 中 【不要】 前后缺少空格
 11. 第333行 [原理应用程序视图、配置文件等。] 修改为 [远离应用程序视图、配置文件等。]
 12. 第345行 [以下步骤可移除 IIS 惊叹文件处理程序（在服务器层级或网站层级）：] 修改为 [以下步骤可移除 IIS 静态文件处理程序（在服务器层级或网站层级）：]
 13. 第360行 [这将确保您创建的应用程序能明确隔离客户端侧和服务器侧源代码，此举能防止服务器侧的代码被泄露。] 修改为 [这将确保您创建的应用程序的客户端和服务器端内容源代码，此举能防止服务器源代码被泄露。]

@alexinea

**Comment by alexinea** [comment]
已根据 @mengshuaiyang 的意见进行的修订，其中对第7和第13条意见有所保留，未按建议修正。
