### ISSUE TITLE
DOC-05-3-8 issue

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/aspnetcore-doc-cn#223]
Document Url : https://docs.asp.net/en/latest/mvc/views/dependency-injection.html

中英对照：https://github.com/YaoaY/aspnetcore-doc-cn/blob/trans-views-di/aspnet/mvc/views/dependency-injection.rst

**Comment by kiler398** [comment]
重新关联到 #266

**Comment by kiler398** [comment]
本issue作废
