### ISSUE TITLE
【翻译】DOC-06-2 Integration Testing

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/aspnetcore-doc-cn#227]
Document Url : https://docs.asp.net/en/latest/testing/integration-testing.html

翻译地址：https://github.com/wjhgzx/aspnetcore-doc-cn/blob/master/aspnet/testing/integration-testing.rst

**Comment by alexinea** [comment]
请查看 #175

**Comment by SeayXu** [comment]
#288
