### ISSUE TITLE
【翻译】DOC04-01 Overview of ASP.NET MVC

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#253]
原文：https://docs.asp.net/en/latest/mvc/overview.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/overview.rst

**Comment by jack2gs** [comment]
@ijiechen 审核完毕，你改下吧。

行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
31 |  用户请求被引导到控制器 | 用户请求被路由到控制器 | 感觉路由更好理解吧
45、83 | 说明| note | rst的标签是note，否则解析不出来 
45 | 这样分离允许模型被创建并可以依赖于虚拟的表现中测试。 | 这样分离允许不依赖于视觉表现创建并测试模型。 |
59 | 说明| note | rst的标签是note，否则解析不出来
41、69 | 用户接口| 用户界面 | 注意总共有四处。用户界面更好理解，感觉
69 | 如果你发现需求，要在 | 如果你发现需要在 | 
99 | 支持有好的测试驱动设计/开发（TDD）开发方式并且使用最新的 Web 标准。 | 支持友好的测试驱动开发（TDD）开发方式并且使用最新的 Web 标准。 | 
132 | 可搜索的的 | 可搜索的 | 
132 | 是建立在 :doc:`ASP.NET Core 路由 </fundamentals/routing>`上的 | 是建立在 :doc:`ASP.NET Core 路由 </fundamentals/routing>` 上的 | 格式解析错误
167 | ASP.NET Core MVC :doc:`模型建立 </mvc/models/model-binding>`  | ASP.NET Core MVC :doc:`模型绑定 </mvc/models/model-binding>`  | 格式解析错误
167 | 识别出传入请求数据的工作 | 识别传入请求数据的工作 |
167 | 以为你的模型对象添加数据批注校验特性装饰 | 通过为你的模型对象添加数据批注校验特性装饰 |
220 | 且利用 `jQuery Validation <http://jqueryvalidation.org/>` | | 格式解析错误
230 | ASP.NET Core 内置了对 :doc:`依赖注入 (DI) </fundamentals/dependency-injection>`的支持 | ASP.NET Core 内置了对 :doc:`依赖注入 (DI) </fundamentals/dependency-injection>` 的支持 | 格式错误
291 | 简便的 | 简单地 | 
311 | use the the | 使用 | 
311 | 清晰的 | 清晰地 | 
323 | 分部视图  | 部分视图  | 
361 | 它们指向 HTML 元素基于元素名、属性名或父标签 | 它们通过元素名、属性名或父标签定位 HTML 元素
373 | | | 缩进错误
400 | 分部视图 | 部分视图 |
