### ISSUE TITLE
【翻译】DOC04-03-01 Views Overview

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#258]
原文：https://docs.asp.net/en/latest/mvc/views/overview.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/views/overview.rst

**Comment by YaoaY** [comment]
#402

**Comment by jack2gs** [comment]
@YaoaY 
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
97 | | | 缩进有问题，格式错误
127 | 惯例 | 约定 | 约定优于配置，convention翻译成约定比较好
272 | | | 没这行，去掉

**Comment by YaoaY** [comment]
@jack2gs 已经修改并提交。
