### ISSUE TITLE
【翻译】DOC04-03-06-01 Introduction to Tag Helpers

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#263]
原文：https://docs.asp.net/en/latest/mvc/views/tag-helpers/intro.html

**Comment by liuhaoyang** [comment]
翻译稿：https://github.com/liuhaoyang/aspnetcore-doc-cn/blob/introduction_to_tag_helpers/aspnet/mvc/views/tag-helpers/intro.rst

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
30 |  所以保证客户端得到当前图像 | 因此保证客户端得到当前图像 | 
30 | 在公共的 Github 存储库和以 NuGet 包的方式更容易获得 | 在公共的 Github 存储库中的和以 NuGet 包的方式存在的可用资源
52 | 一种让你使用仅在服务器上可用的信息来更有效并且能够生成更强大，可靠和可维护代码的方式。 | 一种使用仅在服务器上可用的信息让你更高效并且能够生成更强大，可靠和可维护代码的方式 | 注意去掉句末的句号
81 | | | 这句之前应该加个空行
93 | 应用命名为 | 应用，命名为 |
102 | 指示使 Tag Helpers 在视图中可用 | 指令使 Tag Helpers 在视图中可用 |
102 | 默认继承所有的视图文件在 Views 和子目录 | 默认继承所有的在 Views 和子目录中的视图文件 | 
102 | 我们使用 “*” 对于所有 Tag Helpers | 对于所有 Tag Helpers，我们使用 “*” |
106 | 暴露这个项目中的所有 Tag Helpers | 这个项目中，为了暴露所有的Tag Helpers |
127 | 使用 FQN 在视图中添加一个 Tag Helper | 为了使用 FQN 在视图中添加一个 Tag Helper |
157 | 文件是附加的 | 文件是追加的 | 
161 | 选择退出个别元素 | 禁用个别元素 | 
174 | 在你添加退出字符之后，元素和 Tag Helper 特性将不再显示在一个单独的字体中 | 在你添加退出字符之后，元素和 Tag Helper 特性将不再以特殊的字体显示 |
185 | Tag Helper 前缀设置为``th:``，因此只有那些使用前缀 ``th:`` 的元素支持 Tag Helpers  | | 格式错误
215 | （ “@” 和 “<>” 符合在下面）。 | （ 下面含有“<>” 的“@”符号）。 |
221 | 如 ``fieldse |  | 格式错误
237 | 智能感知声明完成 | 智能感知语句完成 |

**Comment by liuhaoyang** [comment]
修正 https://github.com/dotnetcore/aspnetcore-doc-cn/pull/424

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
268 | HTML elements 在 Razor 视图中附加到 HTML 元素 |   Tag Helpers在在 Razor 视图中附加到 HTML 元素 | 
276 | 接下来的连个参数 | 接下来的两个参数 | 
284 | 一个前端设计师（一些人熟悉 HTML/CSS/JavaScript 和其他客户端技术但是不熟悉 C# 和 Razor），大部分的路线是不相关的 | 对于一个前端设计师（一些人熟悉 HTML/CSS/JavaScript 和其他客户端技术但是不熟悉 C# 和 Razor）来讲，该行的大部分是陌生的。|
300 | 它转换驼峰名称属性到每一个首字母大写的属性名称组成的句子 | 它转换驼峰名称属性到由每一个首字母大写的属性名称组成的句子 | 
364 |  |  | 缩进错误
364 | Visual Studio 编辑器帮助你编写在 Tag Helper 注册表单中方法的 all 标记 | Visual Studio 编辑器帮助你编写在 Tag Helper 注册表单中方法的 all 标记，Visual Studio 没有提供帮助给 HTML Helpers 方法的代码 | 使用Tag Helper 注册表单中的方法，Visual Studio 编辑器会帮助你编写所有标记，而Visual Studio 没有给 HTML Helpers 方法的代码提供帮助 | “所有”黑体显示
375 | Web Server controls have a non-trivial lifecycle that can make developing and debugging difficult. |  | 这句未翻译
379 | Web 服务器控件允许你给通过客户端控制的客户端文档对象模型（ocument Object Model ，DOM）添加功能 | Web 服务器控件允许你给通过客户端控件给客户端文档对象模型（ocument Object Model ，DOM）添加功能
383 | Web 服务器包含 | Web 服务器控件包含 | 
399 | 通常来自 ``TagHelper`` |  Tag Helpers 通常继承自 ``TagHelper`` | 
420 | `TagHelperSamples on GitHub <https://github.com/dpaquette/TagHelperSamples>`__ 包含 Tag Helper 样本和 `Bootstrap <http://getbootstrap.com/>`__  工作.  | `TagHelperSamples on GitHub <https://github.com/dpaquette/TagHelperSamples>`__ 包含与`Bootstrap <http://getbootstrap.com/>`__ 一起工作的 Tag Helper 示例。
