### ISSUE TITLE
【翻译】DOC04-03-09 View Components

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#267]
原文：https://docs.asp.net/en/latest/mvc/views/view-components.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/views/view-components.rst

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
36 | 部分视图 | 局部视图 |
53 | 部分视图 | 局部视图 |
75 | 我们将详细的检查每一个步骤 | 我们将详细地检查每一个步骤 | 
89 | 试图组建类 | 视图组建类
92 | 使用 [ViewComponent] 特性, 或者其派生类来装饰一个类 | 装饰一个带有[ViewComponent] 特性或者继承自它的类
107 | 不参与控制器生命周期, 意味着 | 不参与控制器生命周期，意味着 | 标点符号错误
123 | 通常视图组件初始化模型并传递它到视图通过调用View 方法 | 通常视图组件初始化模型并通过调用View 方法传递它到视图 | 
125 | InvokeAsync |  | 格式错误，应该是内联的代码块
126 | 通常初始化模型并传递它到视图通过调用 ViewComponent View 方法 | 通常初始化模型并通过调用 ViewComponent View 方法传递它到视图 | 
128 |  终结点, 它们 | |标点符号错误
129 | 的任何细节。 | 的任何细节 | 去掉标点
196 | | | 标点符号错误
234 | 比如,我们 | 比如，我们 | 标点错误
243 | 用的方法, 并且 | 用的方法，并且 |
257 | 文件夹.。 | 文件夹。 | 
269 | 你可以到特定控 | 你可以添加到特定控 | 
378 |  |  | 标点错误
409 | 额外的资源 | 附加的资源 |
