### ISSUE TITLE
【翻译】DOC04-04-05 Testing Controller Logic

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#274]
原文：https://docs.asp.net/en/latest/mvc/controllers/testing.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/controllers/testing.rst

**Comment by SeayXu** [comment]
@jijiechen 审核

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
---- | ---- | ----- | -----
67 | 时，要确保只聚焦于操作本身的行为。控制器单元测试避 | | 标点符号错误
97 | HTPP POST Index | HTTP POST Index | 
121 | 这个例子中所采用的 Moq 库便于将可验证的，或者说 “严格的”，与不可验证的 mock （也称为 “宽松的” mock 或 stub）混合进行 mock 。 | 这个例子中所采用的 Moq 库能够简单地混合可验证的，“严格的”及带有不可验证mock（也称为 “宽松的” mock 或 stub）的mock。 |
183 | 不过，集成测试往往比集成测试慢得多。 | 不过，集成测试往往比单元测试慢得多。 |
