### ISSUE TITLE
【翻译】DOC-05-01 Unit Testing

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#287]
原文地址：https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-dotnet-test

翻译地址：https://github.com/wjhgzx/aspnetcore-doc-cn/blob/master/aspnet/testing/unit-testing.rst

**Comment by SeayXu** [comment]
@wjhgzx 将翻译文档同步到主仓库
@UtilCore 审核
