### ISSUE TITLE
【翻译】DOC-05-03 Testing Controller Logic

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#289]
原文：https://docs.asp.net/en/latest/mvc/controllers/testing.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/controllers/testing.rst

**Comment by YaoaY** [comment]
#431

**Comment by SeayXu** [comment]
#274  DOC04-04-05 Testing Controller Logic
与 #274  相同
