### ISSUE TITLE
 【翻译】DOC-06-03 Getting Started with ASP.NET Core and Entity Framework 6

### ISSUE THREAD

**Issue by kiler398** [dotnetcore/aspnetcore-doc-cn#290]
原文地址：https://docs.asp.net/en/latest/data/entity-framework-6.html
翻译：https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/data/entity-framework-6.rst

**Comment by ijiechen** [comment]
本篇已翻译

**Comment by SeayXu** [comment]
#399
