### ISSUE TITLE
【翻译】DOC-06-01-04 Migrations

### ISSUE THREAD

**Issue by seayxu** [dotnetcore/aspnetcore-doc-cn#443]
原文:https://docs.asp.net/en/latest/data/ef-mvc/migrations.html
翻译:https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/data/ef-mvc/migrations.rst

**Comment by kiler398** [comment]
开始翻译

**Comment by kiler398** [comment]
翻译完毕
