### ISSUE TITLE
【翻译】DOC-06-01-09 Inheritance

### ISSUE THREAD

**Issue by seayxu** [dotnetcore/aspnetcore-doc-cn#448]
原文:https://docs.asp.net/en/latest/data/ef-mvc/inheritance.html
翻译:https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/data/ef-mvc/inheritance.rst

**Comment by alexinea** [comment]
翻译已由 #463 合并入 dev 分支
