### ISSUE TITLE
make html出错

### ISSUE THREAD

**Issue by jack2gs** [dotnetcore/aspnetcore-doc-cn#56]
出现如下错误：
Running Sphinx v1.4.3
making output directory...
WARNING: the config value 'epub_copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
loading translations [zh_CN]... done
loading pickled environment... not yet created
loading intersphinx inventory from ../common/api.inv...
building [mo]: targets for 0 po files that are out of date

Encoding error:
'ascii' codec can't decode byte 0xef in position 15: ordinal not in range(128)
The full traceback has been saved in /var/folders/x_/xgxxwlsn0pz0t3021csdttvm0000gn/T/sphinx-err-bNaEMt.log, if you want to report the issue to the developers.
make: *** [html] Error 1

**Comment by alexinea** [comment]
Open aspnet/conf.py.

Pls remove Chinese characters on line 52 and comment code on line 67.
