### ISSUE TITLE
DOC-05-3-2 重新关联

### ISSUE THREAD

**Issue by xbuilder** [dotnetcore/aspnetcore-doc-cn#68]
[原文地址](https://docs.asp.net/en/latest/mvc/views/layout.html)
[中英对照](https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/mvc/views/layout.rst)
翻译完毕，请审核

**Comment by YaoaY** [comment]
1. 

> 这个布局为应用程序定义了一个高级视图模板。
建议修改为：

> 这个布局为应用程序中的视图定义了一个顶层模版。

2.
> Sections only flow from views .

这个我感觉可以直接意译成：> Section 只能来自于视图中的定义。而不能引用自....

因为 Section 确实只能在 View 中定义，同时只能在 layout 中渲染出来。其过程就是从视图流向布局，这可能是原文使用 flow from 的原因。

**Comment by YaoaY** [comment]
3.
> 指令可以指定在一个 _ViewImports.cshtml 文件中并被多个视图使用。

建议修改成：

> 由多个视图使用的指令可以在 _ViewImoports.cshtml 文件中指定。


4.
>在ASP.NET Core MVC 应用程序中， _ViewImports.cshtml 通常被放置在 Views 文件夹根目录下。在运行顺序上，首先运行在根目录下的 _ViewImports 文件，然后运行 Controller 相关文件夹下的 _ViewImports``文件，所以在根目录中 ``_ViewImports 文件里指定的设定可能会被覆盖掉。

中间漏了一句：

>在ASP.NET Core MVC 应用程序中， _ViewImports.cshtml 通常被放置在 Views 文件夹根目录下。_ViewImports.cshtml 也可以放在控制器相关的视图文件夹下面，在这种情况下，它将只作用于该文件夹下的视图。在运行顺序上，首先运行在根目录下的 _ViewImports 文件，然后运行 Controller 相关文件夹下的 _ViewImports``文件，所以在根目录中 ``_ViewImports 文件里指定的设定可能会在子目录中被覆盖掉。

**Comment by YaoaY** [comment]
5.
> 如果你有代码需要在任何视图之前运行

建议:

>如果你有代码需要在**每个**视图之前运行

6.
>比如 :ref:`ViewImports.cshtml <viewimports>`，_ViewStart.cshtml 也有优先级分层。

建议：

>就像 :ref:`ViewImports.cshtml <viewimports>` ，_ViewStart.cshtml 也有优先级。

最后一句.

>这些文件是应用程序级别的，应该直接放在 /Views 文件夹下。

建议：

> 如果这些文件是应用程序级别的，应该直接放在 /Views 文件夹下。

@xbuilder 

**没有发现其他问题**。

**Comment by kiler398** [comment]
#260 重新关联issue
