### ISSUE TITLE
【翻译】DOC-02-4-3 Adding a view

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#79]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/adding-view.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/adding-view.rst

**Comment by YaoaY** [comment]
#86 
#87 
#91 
#93
