### ISSUE TITLE
【翻译】DOC-02-4-4 Adding a model

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#80]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/adding-model.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/adding-model.rst

**Comment by alexinea** [comment]
#113

**Comment by mengshuaiyang** [comment]
1. 第229行 ``模型（Model）``后多了一个空格，导致显示效果出错
![360 1688042710198138](https://cloud.githubusercontent.com/assets/11664228/16048528/055990e2-3287-11e6-9137-cd2c1b6e78d1.png)

@xbuilder

**Comment by SeayXu** [comment]
@mengshuaiyang @xbuilder 这个我知道的，我准备提交pr的
