### ISSUE TITLE
【翻译】DOC-02-3-5 Working with SQL Server LocalDB

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#81]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/working-with-sql.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/working-with-sql.rst

**Comment by mengshuaiyang** [comment]
1. 第13行 ``ApplicationDbContext`` 前面的空格去掉
2. 第23行 最后加空行，去掉后面代码行的显示
![360 17231231464364](https://cloud.githubusercontent.com/assets/11664228/16046808/4e1d1292-3280-11e6-8b7c-3b9ed842d6a0.png)
3. 第31行 行前面去除掉空格
4. 第77行 最后加空行，去掉后面代码行的显示（同问题2）
5. 第85行 最后加空行，去掉后面代码行的显示（同问题2）
6. 第93行 去除掉前面的空格
7. 第93行 最后加空行，去掉后面代码行的显示（同问题2）

@ChujianA

**Comment by SeayXu** [comment]
41行：默认情况下，LocalDB数据库创建的 "\*.mdf" 文件在 *C:/Users/\<user>* 目录下。
这里的 \<user> 换成中文 用户名 呢，可以考虑下

45行：从 **View** 菜单中，打开 **SQL Server对象资源管理器（SQL Server Object Explorer ）**（SSOX）。
#124
