### ISSUE TITLE
【翻译】DOC-02-3-6 Controller methods and views

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#82]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/controller-methods-views.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/controller-methods-views.rst

**Comment by stoneniqiu** [comment]
1.Visual studio 会自动导入 using System.ComponentModel.DataAnnotations; 代码。感觉有点绕，建议直接翻译成 Visual studio 会自添加 using System.ComponentModel.DataAnnotations;。 
2.他们默认会标注为灰色字体-- 建议：它们默认显示灰色字体。 “标注”一般是指添加一段说明文字。 
3.更新后的代码： 后面的代码没显示出来。 
5.MVC Core Anchor Tag Helper 自动生成后面又一段代码没显示出来。
(Controller 方法其实就是指带 action 方法。)-->去掉‘带’字、 
6.The [Bind] attribute is ... 这一段未翻译。 
7.The scaffolded code 建议翻成脚手架代码而不是搭建的代码。 
8.The <input> elements are in an ... 一段未翻译 
9.模型绑定机制以发送表单数据并创建 Movie 对象作为 movie 参数。-->模型绑定机制将作为movie参数传递过来的表单数据创建为一个movie对象。 
10.代码把用户重新引导到 MoviesController 类的 Index 方法，显示 Moive 集合的页面，包含了最新的数据改动。-- 语句不通。建议意译：程序跳转到MoviesController的Index方法，这个页面展示了最新改动的Movie集合。 smile

**Comment by xbuilder** [comment]
@kiler398 
针对 @stoneniqiu 的审批意见回复：
1.【无关紧要】保留原文和稍作修改都可，意思都符合。
2.【建议调整】附议，They show up by default in a light grey font->它们默认以灰色字体出现
3.【并非问题】此处代码是通过脚本生成，需要进行make html后查看
5.【并非问题】同3
6.【此段有翻译】建议将 attribute 翻译为 特性
7.【建议调整】建议改为 基架生成的代码
8.【确实翻译漏了】![image](https://cloud.githubusercontent.com/assets/10357081/16085998/93368086-3350-11e6-8f8b-2348cd9d6c32.png)
9.【建议修改】:doc:`模型绑定 </mvc/models/model-binding>` 机制以发送表单数据并创建 ``Movie`` 对象作为 ``movie`` 参数。
调整为
:doc:`模型绑定 </mvc/models/model-binding>` 机制使用表单提交过来的数据创建了一个 ``Movie`` 对象作为 ``movie`` 参数。
10.【建议修改】这段代码将用户重定向到 MoviesController 类的 Index 方法，这个页面显示了改动后最新的Movie集合

**Comment by mengshuaiyang** [comment]
1. 第73行 【Controller 方法其实就是指带 action 方法。】 修改为 【Controller 方法其实就是指代 action 方法。】
2.第95行 去除前面的空格（否则将导致无法显示）
3.第95行 前面【`over-posting】前面加空格否则将导致链接效果失效
4.第130行 【基架生成的代码使用几个 Tag Helper 方法来简化 HTML 标记。 - 】标记。后面的 - 去掉
5.第132行 【/ Movies】中间的空格去掉，修改为【/Movies】
6.第150行 【所有的如 创建、编辑、删除、或者其他的修改数据的方法 在不同的  ``[HttpPost]`` 方法重载中执行】 修改为 【所有的如：创建、编辑、删除或者其他的修改数据的方法，在不同的  ``[HttpPost]`` 方法重载中执行】

**Comment by YaoaY** [comment]
When the scaffolding system created the Edit view, it examined the Movie class and created code to render <label> and <input> elements for each property of the class. The following example shows the Edit view that was generated by the visual studio scaffolding system:

当搭建的系统创建 Edit 视图的时候，他会检查 Movie 类并创建代码使用 <label> 以及 <input> 元素来来呈现类的每一个属性。下面的代码展示了 visual studio 脚手架工具生成的 Edit 视图：

建议：
在基架系统创建 Edit 视图的时候，会检查 Movie 类并为它的每个属性生成代码以呈现 <label> 和 <input> 元素。下面的例子展示了 Visual Studio 基架系统生成的 Edit 视图：

**Comment by YaoaY** [comment]
> 是 ASP.NET Core 中最受欢迎的功能之一

建议：

> 是 ASP.NET Core 中最受欢迎的新功能之一

**Comment by YaoaY** [comment]
`The [Bind] attribute is one way to protect against over-posting. You should only include properties in the [Bind] attribute that you want to change. See Protect your controller from over-posting for more information. ViewModels provide an alternative approach to prevent over-posting.`

> [Bind] 特性是防止 over-posting (过度提交，客户端可能发送比期望还多的数据，比如只需要2个属性但是发送了3个属性)的一种方法。你只需要在你想要改变的中的属性上使用 [Bind]。请参阅 Protect your controller from over-posting 获取更多信息， ViewModels 提供另一个方法来防止over-posting。

建议：

>[Bind] 特性是防止 重复提交 的一种方法。你应该只把需要改变的属性包含到 [Bind] 特性中。请参阅 Protect your controller from over-posting 获取更多信息， ViewModels 提供了另一种防止重复提交的方法。
