### ISSUE TITLE
【翻译】DOC-02-3-7 Adding Search

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#83]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/search.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/search.rst

**Comment by stoneniqiu** [comment]
worktitle中没更新么  初见

**Comment by stoneniqiu** [comment]
1.将添加搜索功能在Index方法中-- 顺序改下--将在Index方法中添加搜索功能。 
2.Lambdas是基于LINQ查询的查询的方法，作为标准查询操作方法的参数-->Lambads是用于基于Linq查询方法，作为标准查询操作方法的参数。（不然Lambdas是方法还是参数有歧义） 
3.相反，查询执行被延迟 ---> 相反，查询将延迟执行（意译更通顺）。 
4.If you change the signature of the Index method to have a parameter named id,the id parameter will match the optional{id} placeholder for the default routes set in Startup.cs.-->如果改变Index方法的签名，增加一个名为'id'的参数，那么因为在Startup类中设置的默认路由，这个id参数将会匹配{id}这个可选的占位符。 
5.应该在下面的[HttpPost] Index方法中添加[HttpPost]。-- 去掉第一个HttpPost 
6.action invoker 建议翻译成 action 调用器，这里毕竟是一个名次，‘action调用将匹配’...有点奇怪 
7.即使添加Index方法的这个[HttpPost]版本 -->即使添加HttpPost的 
8.form field value --> 表单值。 
9.You can see the search parameter and token in the request body.-- 你可以在请求体中看到查询参数和令牌。 
10.you can't capture that search information to bookmark or share with others-->（翻译的不通顺）建议：你不能捕获查询信息后添加到书签或者分享给他人。 
11.添加搜索类型--建议-- 添加类型搜索 
12.by projecting - 直接翻译成“通过投影”太不通顺了。The SelectList of genres is created by projecting the distinct genres -->意译为：这个类型的SelectList代表的是不同的类型。 
13.Adding search by genre to the Index view 在Index视图中添加搜索类型的模型 -- 在Index视图中添加类型搜索。

**Comment by stoneniqiu** [comment]
文中很多地方翻译的比较生硬，还需要通过表达顺序和意译来润色一下。

**Comment by mengshuaiyang** [comment]
1. 第13行 [在本节中，我们为 ``Index`` 方法添加查询功能，使我们能够根据电影的 *genre* 或 *name* 进行查找。] 修改为 [在本节中，你可以为 ``Index`` 方法添加查询功能，使其能够根据 *genre* 或 *name* 进行查找电影。]
 2. 第55行 [注意] 修改为 [Note]
 3. 第55行 [在数据库中， [Contains][1] 方法被翻译为SQL语句中不区分大小写的[LIKE][2] 。]
 4. 第80行 [重命名被影响到的代码会被高亮。] 修改为 [会被重命名的代码会高亮显示。]
 5. 第92行 [上一个 ``Index`` 方法：] 修改为 [修改前的 ``Index`` 方法：]
 6. 第102行 [修改后的 ``Index`` 方法如下:] 修改为 [修改后的 ``Index`` 方法:]
 7. 第118行 [现在再把它改回来参数名复原回  ``searchString`` 。] 修改为 [现在再把它改成原来的参数  ``searchString`` 。]
 8. 第167行 [然而，尽管我们添加了 ``[HttpPost]`` 版的 ``Index``，它在实现的时候仍然存在一些局限性。] 修改为 [然而，添加了 ``[HttpPost]`` 版本的 ``Index``，在实现的时候仍然存在一些局限性。]
 9. 第167行 [Start the [F12 tool][3]来验证。] 修改为 [[F12 tool][3]：]
 10. 第195行 [查询会跳转到 HttpGet Index 方法如果本身存在 HttpPost Index 方法。] 修改为 [如果存在 HttpPost Index 方法,查询会跳转到 HttpGet Index 方法。]
 11. 第201行 [添加按照 Genre 查询] 作为标题的后面一行要加 ----
 12. 第213行 [电影-genre 视图模型包含：] 修改为 [move-genre 视图模型包含：]
 13. 第233行 [下面的代码包含 ``LINQ`` 查询来返回数据库中的所有 genre。] 修改为 [下面代码是通过LINQ 语句从数据库中检索所有genre数据。]
 14. 第242行 [SelectList 的genres属性通过 Distinct 方法投影查询创建（我们不想选择列表中出现重复的数据）。] 修改为 [SelectList 的genres通过 Distinct 方法查询创建（我们不想选择列表中出现重复的genres数据）。]
 15. 第251行 [在 Index 视图中添加通过 genre 检索]  作为标题的后面一行要加 ----


  [1]: http://msdn.microsoft.com/en-us/library/bb155125.aspx
  [2]: http://msdn.microsoft.com/en-us/library/ms179859.aspx
  [3]: https://dev.windows.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/

**Comment by kiler398** [comment]
2.和A大讨论过，可以汉化
3.LIKE 原文和 SQL 在一起的，应该不需要分开，SQL语句是我加上的便于意思表达意思
8.我觉尽管要保留，因为原文有
242.投影查询指代projecting 不能去掉

**Comment by jack2gs** [comment]
原文：现在，查询信息是作为表单数据发送到服务器的，你可以通过 F12 开发者工具或者优秀的抓包工具 Fiddler tool。F12 tool。
建议修改:现在，查询信息是作为表单数据发送到服务器的，你可以通过 F12 开发者工具或者优秀的抓包工具 Fiddler tool。启动F12 tool：
备注：参考了英文原版

**Comment by jack2gs** [comment]
原文：测试程序并分别通过 genre 或者 电影标题以及两个条件同时进行检索
建议修改：测试程序并分别通过 genre 或者电影标题以及两个条件同时进行检索
备注：多了个空格

**Comment by mengshuaiyang** [comment]
@jack2gs 
已根据建议修改。
