### ISSUE TITLE
【翻译】DOC-02-3-8 Adding a New Field

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#84]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/new-field.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/new-field.rst

**Comment by SeayXu** [comment]
@UtilCore 这篇文章我已审过一遍了，这是就是修正稿

**Comment by jack2gs** [comment]
原文：现在，查询信息是作为表单数据发送到服务器的，你可以通过 F12 开发者工具或者优秀的抓包工具 Fiddler tool。F12 tool。
建议修改:现在，查询信息是作为表单数据发送到服务器的，你可以通过 F12 开发者工具或者优秀的抓包工具 Fiddler tool。启动F12 tool：
备注：参考了英文原版

**Comment by jack2gs** [comment]
原文：应用程序无法工作直到我们更新了数据库包含新的字段
建议修改：直到我们更新了数据库包含新的字段，应用程序才能工作
备注：感觉这样更符合写作习惯
