### ISSUE TITLE
【翻译】DOC-02-3-9 Adding Validation

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#85]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/validation.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/validation.rst

**Comment by mengshuaiyang** [comment]
1. 第1行 [为模型添加验证] 修改为 [添加验证]
 2. 第10行 [在本章节中你将为 ``Movie`` 模型类添加验证] 修改为 [在本章节中会将验证逻辑添加到 ``Movie`` 模型]
 3. 第15行 [ASP.NET MVC 的核心原则之一是[DRY][1]("不要自己重复")。] 修改为 [ASP.NET MVC 的核心原则之一是[DRY][1]("不要重复自己")。]
 4. 第15行 [这样大大的减少了需要编写的代码量，从而使你的代码编写不容易出现错误，而且更容易维护。] 修改为 [这减少了需要编写的代码量，并且使你编写代码出错误更少的和易于维护的代码。]
 5. 第24行 [它也同时提供了一些格式属性比如 ``DataType``  用来帮你格式化而非验证功能。] 修改为 [它也同时提供了一些格式属性比如 ``DataType``  用来帮你格式化而非提供验证功能。]
 6. 第34行 [验证属性可以指定应用到模型属性需要执行的验证行为] 修改为  [验证属性指定了您想要将它们应用到模型属性需要执行的验证行为]
 7. 第34行 [空格、数字以及特殊字符都不允许] 修改为 [不允许输入空格、数字以及特殊字符]
 8. 第50行 [如果用户已禁用 JavaScript] 修改为 [以防用户已禁用 JavaScript]
 9. 第52行 [使用 Edit action 方法测试验证，以及相同的验证应用。] 修改为 [在测试验证应用程序里，使用 Edit action 方法测试验证。]
 10. 第66行 [第二个 ``Create`` 的方法（HttpPost 版本）调用 ``ModelState.IsValid`` ，以检查是否有任何验证错误。] 修改为 [第二个 ``Create`` 的方法（HttpPost 版本）调用 ``ModelState.IsValid`` 检查是否有任何验证错误。]
 11. 第66行 [如果您在您的浏览器禁用了JavaScript，客户端验证被禁用，HTTP POST版本的 ``Create`` 方法调用 ``ModelState.IsValid``，以检查是否存在任何验证错误。] 修改为 [如果您在您的浏览器禁用了 JavaScript，客户端验证将被禁用，HTTP POST版本的 ``Create`` 方法会调用 ``ModelState.IsValid``检查是否存在任何验证错误。]
 12. 第86行 [下面是您在本教程前面用脚手架生成的 Create.cshtml 视图模板的一部分。] 修改为 [下面是您在本教程前面用基架生成的 Create.cshtml 视图模板的一部分。]
 13. 第95行 [控制器和 ``Create`` 视图模板不知道什么实际的验证规则正在执行或特定的错误消息显示，这种做法非常好。] 修改为 [控制器和 ``Create`` 视图模板不知道任何有关正在执行的实际验证规则或特定的错误消息显示。]
 14. 第97行 [如果你想更改的验证逻辑]  修改为 [如果你想更改验证逻辑]
 15. 第110行 [在本示例中我们只像跟踪的日期，而不需要具体时间。] 修改为 [在本示例中我们只想跟踪的日期，而不需要具体时间。]


  [1]: http://en.wikipedia.org/wiki/Don%27t_repeat_yourself

@kiler398

**Comment by SeayXu** [comment]
第15、24、48、110、121、127行中的 括号和引号换成中文符号。

第52、54、66、68、86、95、121、126行中的 **您** 修正为 **你**。

第48行：
原文：你也许无法在 ``Price`` 字段中输入小数点或者逗号。为了让 [jQuery validation](http://jqueryvalidation.org/) 支持非英语文化这样可以用逗号(",")代替小数点，非英语日期格式，你必须实现应用程序本地化。参考 `附加资源`_ 获取更多信息。 不过现在， 我们还是输入像10这样的整数就好了。
修正：你也许不能在 ``Price`` 字段中输入小数点或逗号。为了实现对非英语环境中用逗号(",")来表示小数点，以及非美国英语日期格式的 [jQuery validation](http://jqueryvalidation.org/)，你必须采取措施国际化你的应用程序。查看 `额外的资源`_ 获取更多的信息。现在仅仅输入完整的数字，比如10。

第50行：
原文：请注意，表单自动使用红色边框的突出显示包含无效的数据的文本框，并在每一个旁边提示适当的验证错误消息。
修正：请注意，表单自动使用红色边框突出显示包含无效数据的文本框，并在每一个旁边提示适当的验证错误消息。

第126行：
原文：默认情况下，浏览器将基于您的 [locale](http://msdn.microsoft.com/en-us/library/vstudio/wyzd2bce.aspx) 设置来正确的提供你所需要的数据格式。
修正：默认情况下，浏览器将基于你的 [本地环境](http://msdn.microsoft.com/en-us/library/vstudio/wyzd2bce.aspx) 使用正确的格式渲染数据。
@kiler398

**Comment by mengshuaiyang** [comment]
1. [验证特性指定了你想要应用到模型属性上的验证行为。] 修改为 [验证属性指定了你想要应用到模型属性上的验证行为。]
2.[StringLength 属性可让你设定字符串最大长度，以及最小长度（可选）。] 修改为 [StringLength 属性设定字符串最大长度，以及最小长度（可选）。]
3.[值类型（如decimal， int， float， DateTime）默认情况下，并不需要 [Required] 属性。] 修改为 [值类型（如decimal， int， float， DateTime）本质上是必填的，不需要 [Required] 属性。]
4.[请注意，表单自动使用红色边框突出显示包含无效的数据的文本框] 修改为 [请注意，表单自动使用红色边框突出显示无效数据的文本框]
5.[使用 Edit Action 方法测试验证] 修改为 [使用 Edit 操作方法测试验证]
6.[断点会命中] 修改为[断点会被命中]
7.[非常棒的是，控制器和 Create 视图模板不知道实际执行的验证规则或显示的具体错误消息。] 修改为 [非常棒的是控制器和 Create 视图模板不知道实际执行的验证规则或显示的具体错误消息。]
8.[这意味着，你会充分遵循了 DRY 原则。] 修改为 [这意味着，你充分遵循了 DRY 原则。]
9.[浏览器可以启用 HTML5 特性] 修改为 [浏览器可以启用 HTML5 功能]

**Comment by SeayXu** [comment]
第10行：
原文：以确保在用户试图创建或编辑影片数据时强制执行验证规则
修正：以确保用户在试图创建或编辑影片数据时强制执行验证规则

第135行：
原文：你需要禁用jQuery数据验证日期验证在
修正：你需要禁用jQuery日期验证在

第135行：
原文：在编译你的模型的具体日期的时候这通常不是一个好的做法
修正：在你的模型中编译具体日期通常不是一个好的做法

@xbuilder
