### ISSUE TITLE
【翻译】DOC-02-3-10 Examining the Details and Delete methods

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#88]
Document Urls：https://docs.asp.net/en/latest/tutorials/first-mvc-app/details.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/first-mvc-app/details.rst

**Comment by SeayXu** [comment]
@UtilCore 初次审核完成
