### ISSUE TITLE
【翻译】DOC-02-4 ASP.NET Core on Nano Server

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#90]
Document Urls：https://docs.asp.net/en/latest/tutorials/nano-server.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/tutorials/nano-server.rst

**Comment by mengshuaiyang** [comment]
@xbuilder 

1. 第71行/80行/ 193行 操作命令的注释也翻译一下

**Comment by kiler398** [comment]
你可以使用虚拟硬盘镜只用来内部演示和评估它。不能将该软件在生产环境中使用。请看 https://go.microsoft.com/fwlink/?LinkId=624232 查看具体的预览截止日期信息。

你可以使用虚拟硬盘镜像来进行内部演示和评估。但不能将该软件在生产环境中使用。参考 https://go.microsoft.com/fwlink/?LinkId=624232 查看具体的预览版截止日期信息
，

**Comment by mengshuaiyang** [comment]
1. [ Windows Server Technical Preview 4 ] 修改为 [ Windows Server Technical Preview 5 ] （原英文已改）
2.Introduction 第一段 参考原文英文重新修正翻译
3.Connecting to your Nano Server Instance using PowerShell Remoting 第三段参考原文英文重新修正翻译
4.Installing the HttpPlatformHandler Module 和 Enabling the HttpPlatformHandler 参考原文 Installing the ASP.NET Core Module、Installing IIS、Installing the ASP.NET Core Module、Enabling the ASP.NET Core Module、Installing .NET Core Framework翻译
5.Publishing the application 原文新增了第二段，需翻译

**Comment by jack2gs** [comment]
行号 | 原文 | 建议修改 | 备注
------ | ------- | ------ | ------
232 | 你可以在 PowerShell 远程会话中执行以下 PowerShell 脚本来在 Nano Server 上启用 HttpPlatformHandler 组件。 | 因为我们令 IIS 在 8000 端口监听和转发请求到我们的应用程序，我们需要开放这个端口的 TCP 通信。 | 我记得英文语法里have有使令的含义，参考原文，建议修改过

**Comment by mengshuaiyang** [comment]
1. 第19行 [本教程使用 Windows Server Technical Preview 5 中的预发行版本的 Nano Server 安装选项。] 修改为 [本教程使用 Windows Server Technical Preview 5 预发行版本中的 Nano Server 安装选项。]
 2. 第19行 [你可以使用虚拟硬盘镜只用来内部演示和评估它。不能将该软件在生产环境中使用] 修改为 [你可以在虚拟硬盘映像中用来内部演示和评估，但不能在生产环境中使用该软件。]
 3. 第19行 [请看 https://go.microsoft.com/fwlink/?LinkId=624232 查看具体的预览截止日期信息。] 修改为 [可通过 https://go.microsoft.com/fwlink/?LinkId=624232 查看预览版本的截止日期信息。]
 4. 第40行 [提供更小的安装体积，更好的安全性以及更好的服务性能] 修改为 [提供更小的安装体积、更好的安全性以及更好的服务性能]
 5. 第51行 [你需要发布一个存在的 ASP.NET Core 应用程序。确保你的程序是构建在 64 位 进程中运行的。] 修改为 [你需要发布一个已有的 ASP.NET Core 应用程序，并确保你的程序是构建在 64 位 进程中运行的。]
 6. 第137行 [从 PowerShell 库平台（PowerShell gallery）中添加 `NanoServerPackage` provider，一旦 provider 被安装或者导入，你就可以安装 Window 包了。] 修改为 [从 PowerShell 库平台（PowerShell gallery）中添加 `NanoServerPackage` 提供程序(provider)，一旦提供程序(provider)被安装或者导入，你就可以安装 Window 包了。]
 7. 第154行遗漏翻译
 8. 第159行 [The ASP.NET Core Module 是一个适用于 IIS 7.5 及以上版本的组件] 修改为 [ASP.NET Core Module 是一个适用于 IIS 7.5 及以上版本的组件]
 9. 第159行 [安装之后你需要复制以下文件：] 修改为 [安装之后您需要将以下文件复制到我们前面创建的共享文件]
 10. 第255行 [发布好的 Web 应用程序可以通过浏览器打开 ``http://<nanoserver-ip-address>:8000`` 链接访问到。] 修改为 [发布好的 Web 应用程序可以通过浏览器打开 ``http://<nanoserver-ip-address>:8000`` 链接访问。]

**Comment by SeayXu** [comment]
第75行：
原文：打开一个**提升过权限**的 PowerShell 窗口
建议：打开一个**授权**的 PowerShell 窗口

第105行：
原文：在 Nano server 上创建文件共享这样可以直接拷贝发布的程序，在远程服务器上运行**下述**命令
建议：在 Nano server 上创建文件共享**，**这样可以直接拷贝发布的程序，在远程服务器上运行**下面的**命令

第115行：Windows Explorer 在计算机中是 Windows 资源管理器
原文：**上述**命令运行完以后，你就可以在你本机使用 **Windows 文件浏览器**通过
建议：**上面**命令运行完以后，你就可以在你本机使用 **Windows 资源管理器**通过

第123行：
原文：在远程会话中运行下面的命令在防火墙中打开一个端口来监听TCP流量。
建议：在远程会话中运行下面的命令**，**在防火墙中打开一个端口来监听 TCP 流量。

第152行：
原文：为了快速验证**ISS**是否正确安装
建议：为了快速验证 **IIS** 是否正确安装

第159行：
原文：ASP.NET Core Module 是一个适用于 IIS 7.5 及**以上**版本的组件...安装之后**您**需要将以下文件复制到我们前面创建的共享文件
建议：ASP.NET Core Module 是一个适用于 IIS 7.5 及**更高**版本的组件...安装之后**你**需要将以下文件复制到我们前面创建的共享文件

第163行：
原文：在常规机（不是 Nano Server）上运行**下述**拷贝命令
建议：在常规机（不是 Nano Server）上运行**下面**拷贝命令

第214行：
原文：**您**可能需要修改你的
建议：**你**可能需要修改你的

第235行：
原文：在远程会话中运行以下命令在**IIS**中为已发布的应用创建一个新的站点。
建议：在远程会话中运行以下命令**，**在 **IIS** 中为已发布的应用创建一个新的站点。

@kiler398 #190
