### ISSUE TITLE
【翻译】DOC-03-1 Application Startup

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#94]
Document Urls：https://docs.asp.net/en/latest/fundamentals/startup.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/startup.rst

**Comment by SeayXu** [comment]
第36行：
原文：ASP.NET 将继续加载**之（只要符合命名规范即可）**。
建议：**如果它符合命名规范，**ASP.NET 将继续加载它。

第36行：
原文：ASP.NET 将基于命名空间选择其中一个（匹配项目的根命名空间优先，否则**基于命名空间首字母排序后的第一个**）。
建议：ASP.NET 将基于命名空间选择其中一个（匹配项目的根命名空间优先，否则**使用第一个按字母排列的命名空间中的类**）。

第40行：
原文：`Startup`  类能**可选**地在构造函数中接受**依赖项（通过 [依赖注入](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html) 提供）**。通常而言，**应用程序的配置都是**定义于 _Startup_ 类的构造函数之中。
建议：`Startup`  类能**选择性**地在构造函数中接受**通过 [依赖注入](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html)  提供的依赖项**。通常而言，**将要被配置的应用程序的方法**定义于 _Startup_ 类的构造函数之中。

第54行：
原文：一些额外服务**（**比如 `IHostingEnvironmen` 或 `ILoggerFactory`**）**也可以被指定，这些服务**（如果它们可用）**将会被服务器 [注入](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html) 进来。
建议：一些额外服务**，**比如 `IHostingEnvironment` 或 `ILoggerFactory` 也可以被指定，**如果在它们可用情况下，**这些服务将会被服务器 [注入](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html) 进来。

第108行：
原文：你可以非常简单地使用这些服务，只需要在在 `Startup` 类的构造函数或是它的 `Configure` 与 `ConfigureServices` 方法**（的其中一个）**包含合适的接口即可。
建议：你可以非常简单地使用这些服务，只需要在在 `Startup` 类的构造函数或是它的 `Configure` 与 `ConfigureServices` 方法**中的一个**包含合适的接口即可。

第124行：
原文：提供了创建日志**器**的机制。可以在 `Startup`  的构造函数或 `Configure`  方法中使用
建议：提供了创建日志的机制。可以在 `Startup` 的构造函数或 `Configure` 方法中使用

第132行：
原文：看看 `Startup` 类中**的每一个方法，排序按照调用它们的顺序**，下面的服务可被作为参数：
建议：看看 `Startup` 类中**按它们被调用排序的每一个方法**，下面的服务可被作为参数：

#208
@alexinea
