### ISSUE TITLE
【翻译】DOC-03-4 Routing

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#97]
Document Urls：https://docs.asp.net/en/latest/fundamentals/routing.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/routing.rst

**Comment by kiler398** [comment]
@stoneniqiu 请把DOC-04-4 Routing提交到dev

**Comment by stoneniqiu** [comment]
@kiler398  dev 地址是多少

**Comment by kiler398** [comment]
@stoneniqiu 
你的文章还在你自己fork的库里面
 https://github.com/stoneniqiu/aspnetcore-doc-cn/blob/71b6f815b19009a5aae543a4e1464d50668524b2/aspnet/fundamentals/routing.rst

需要你提交pr更新到

https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/routing.rst

**Comment by stoneniqiu** [comment]
终于改完了，啊啊啊啊啊啊

**Comment by mengshuaiyang** [comment]
1. 第63行 [调用 ``Startup`` 类的 ``Configure`` 方法使能路由] 修改为 [调用 ``Startup`` 类的 ``Configure`` 方法使用路由]
 2. 第127行 [定义了 ``route value`` 参数的边界。] 修改为 [定义了路由值参数的边界。]
 3. 第378的翻译在核对一遍

@stoneniqiu

**Comment by stoneniqiu** [comment]
enabled 翻译成‘使用‘不合适吧，本意就是使能。其他两处已经修改。
Routing basics多了一个，其他部分更新了很多，有没有新的rst地址？

**Comment by kiler398** [comment]
@stoneniqiu 
最新rst地址
https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/routing.rst

**Comment by stoneniqiu** [comment]
@kiler398   @alexinea 
终于翻译完了 
https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/routing.rst

**Comment by YaoaY** [comment]
我有一些修改建议，我放在我的分支里，这样可以对比查看一下，弄完我删掉。
对比地址：https://github.com/dotnetcore/aspnetcore-doc-cn/compare/YaoaY/Fix-03-04-Routing?expand=1

@stoneniqiu @SeayXu

**Comment by stoneniqiu** [comment]
https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/routing.rst
修改完了，@YaoaY,@SeayXu @kiler398 @alexinea
