### ISSUE TITLE
【翻译】DOC-03-5 Error Handling

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/aspnetcore-doc-cn#99]
Document Urls：https://docs.asp.net/en/latest/fundamentals/error-handling.html

翻译稿 : https://github.com/dotnetcore/aspnetcore-doc-cn/blob/dev/aspnet/fundamentals/error-handling.rst

**Comment by jack2gs** [comment]
修改建议：
行号 | 原文 | 修改 | 备注
------ | ------- | -------- | ------
1	| 异常处理	错误处理	| 原文是Error Handling，感觉翻译成错误处理比较好。
144 	| ASP.NET MVC 异常处理 | ASP.NET MVC 错误处理 | 原文是Error Handling

**Comment by jack2gs** [comment]
19行，“所有上面所述的一切需要在项目中添加”，建议改为“只需要在项目中添加”
27行，“以上代码包含一段检测代码来确认在调用UseDeveloperExceptionPage之前环境是否就绪”，建议改为“以上代码包含一个检查，以确保添加调用UseDeveloperExceptionPage的环境是开发环境”
27行，“这是一个好的方法”建议改为“这是一个好的实践”
29行，“示例应用程序包括创建一个异常简单的机制的例子”建议改为“示例应用程序包括一个创建异常的简单机制的例子：”
31-35行，引用的代码显示不全
58行，“你可以在最后一个选项卡页面查看到头文件信息”建议改为“你可以在最后一个选项卡页面查看到头信息”
108行，“但是也会同时执行设置页面里面的代码”改为“但是也会执行路径中指定的处理程序”
123行，“在你设计有的应用程序的异常处理行为是请注意以下几点”改为“有的应用程序，在你设计异常处理行为时请注意以下几点”
130行，“基于上述建议将有助于确保您的应用程序保持响应”改为“遵从上述建议将有助于确保您的应用程序保持响应”
135行，“如果服务器在头文件发送出去之前捕获到异常”改为“如果服务器在头信息发送出去之前捕获到异常”
135行，“请求不是被你的应用程序处理而是被服务器处理，而发生任何异常将被服务器的异常处理机制来处理。”改为“那些不是被你的应用程序处理的请求将被服务器处理，并且发生的任何异常将被服务器的异常处理机制来处理。”
142行，“处理异常最为最棘手的地方是在你的应用程序的启动的时候。只有承载层可以处理应用程序的启动过程中发生的异常。”改为“处理异常最为最棘手的地方是在你的应用程序的启动的时候。只有承载层可以处理应用程序的启动过程中发生的异常。”
142行，“发生在你的应用程序的启动异常也会影响服务器的行为”改为“应用程序启动时发生的异常也会影响服务器的行为”
142行，“则默认情况下托管将捕获异常，启动服务器，在非SSL端口上显示一个错误页面”改为“则默认情况下托管将捕获异常，并启动服务器，然后在非SSL端口上显示一个错误页面”
142行，“则错误页面将通过HTTPS服务来代替”改为“则错误页面将通过HTTPS服务生效”
147行，“MVC 当应用程序涉及到错误处理的时候有一些额外的选项”改为“MVC 当应用程序涉及到错误处理的时候有一些额外的选项”
159行，“最好详细说明为什么模型验证失败的原因。”改为“最好详细说明模型验证失败的原因。”

**Comment by jack2gs** [comment]
1.实际操作遇到的问题：我安装的是VS 2015社区版，却发现示例代码无法运行。解决方法：更新“Microsoft ASP.NET and Web Tools”
2.“在系统默认情况下，系统会为普通的http状态码添加一个非常简单纯文本的处理，例如，下面是404无法找到文件状态码返回的结果。”配图实际运行结果和文档不一致，不过应该关系不大。

**Comment by jack2gs** [comment]
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell

**Comment by kiler398** [comment]
#196
